version: 0.2

phases:
  pre_build:
    commands:
      - echo "=== Logging into AWS ECR ==="
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REG
      - export NAME=colorkeys
      - export ARCH=$(uname -m)
      - export HASHLONG=$(git log -1 --pretty=%H --no-merges)
      - export HASHSHORT=$(git log -1 --pretty=%h --no-merges)
      - export TAG=$(git describe --tags --abbrev=0)
      - export IMGLONG=$ECR_REG/$NAME:$TAG-$HASHSHORT-$ARCH
      - export IMGSHORT=$ECR_REG/$NAME:$TAG-$ARCH
      - export DEFAULT=$ECR_REG/$NAME:default-$ARCH
      - echo "NAME: $NAME"
      - echo "ARCH: $ARCH"
      - echo "HASHSHORT: $HASHSHORT"
      - echo "TAG: $TAG"
      - echo "IMGSHORT: $IMGSHORT"
  build:
    commands:
      - echo "=== Docker build started ==="
      - docker build --no-cache -t $IMGLONG --build-arg GIT_COMMIT=$HASHSHORT --build-arg ENGCOMMON_BRANCH=$ENGCOMMON_BRANCH -f docker/Dockerfile .
      - docker tag $IMGLONG $IMGSHORT
      - docker tag $IMGLONG $DEFAULT
  post_build:
    commands:
      - echo "=== Docker build completed ==="
      - echo "=== Pushing docker image ==="
      - docker push $IMGLONG
      - docker push $IMGSHORT
      - docker push $DEFAULT
